# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
