# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hu', '0003_auto_20201006_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='description',
        ),
        migrations.AlterField(
            model_name='pictures',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='hu.PicturesCategory'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hu.PicturesColor'),
        ),
    ]
