# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hu', '0004_auto_20201008_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='color',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='hu.PicturesColor'),
        ),
    ]
